language: java
before_install:
  - sudo apt-get install -qq liblzo2-dev
env:
  - C_INCLUDE_PATH=/usr/include/lzo LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
jdk:
  - openjdk6 # works with 7 too
script:
  - mvn test
  - mvn clean test -P hadoop-old
